### ISSUE TITLE
Compilation error with sprintf.c

### ISSUE THREAD

**Issue by djipi** [cubanismo/skunk_usb#1]
sprintf.c has a compilation error.

"
m68k-aout-gcc -DJAGUAR -DUSE_SKUNK -IC:/SDK/AJaguar/jaguar-sdk/jaguar/include -O2 -Wall -fno-builtin -c -o sprintf.o sprintf.c
sprintf.c:4:19: skunk.h: No such file or directory
sprintf.c: In function `printf':
sprintf.c:196: warning: implicit declaration of function `skunkCONSOLEWRITE'
make: *** [C:/SDK/AJaguar/jaguar-sdk/tools/build/jagrules.mk:13: sprintf.o] Error 1
"

The CINCLUDE appears to not have the skunk include directory.

**Comment by cubanismo** [comment]
Yes, apologies, I had a fix for this pending in my SDK tree.  I've pushed it there now, along with a few other minor Makefile fragment tweaks:

https://github.com/cubanismo/jaguar-sdk/commit/ef34df88146aeecb3ec60a77e5434d5e8edd0998
